// This file is auto-generated by generate-scenes.js.
// Do not edit manually.

import type { SceneDefinition } from "../../types/scenes";

// Chapter 01
import carGloveBox from "./chapter01/car-glove-box";
import carInside from "./chapter01/car-inside";
import carLookRight from "./chapter01/car-look-right";
import cityMap from "./chapter01/city-map";
import storageBack from "./chapter01/storage-back";
import storageExit from "./chapter01/storage-exit";
import storageMirror from "./chapter01/storage-mirror";
import storageOutsideCar from "./chapter01/storage-outside-car";
import storageShelf from "./chapter01/storage-shelf";
import storageVcr from "./chapter01/storage-vcr";

// Chapter 02
import cityMallRestaurantTable from "./chapter02/city-mall-restaurant-table";

export type SceneId =
  | "car-glove-box"
  | "car-inside"
  | "car-look-right"
  | "city-map"
  | "storage-back"
  | "storage-exit"
  | "storage-mirror"
  | "storage-outside-car"
  | "storage-shelf-car-keys"
  | "storage-vcr"
  | "city-mall-restaurant-table"
;

export const scenes: SceneDefinition[] = [
  // Chapter 01
  carGloveBox,
  carInside,
  carLookRight,
  cityMap,
  storageBack,
  storageExit,
  storageMirror,
  storageOutsideCar,
  storageShelf,
  storageVcr,
  // Chapter 02
  cityMallRestaurantTable,
];
export const initialSceneId: SceneId = "storage-back";
