// This file is auto-generated by generate-scenes.js.
// Do not edit manually.

import type { SceneDefinition } from "../../types/scenes";

export type SceneId = string;

export const scenes: SceneDefinition[] = [
];
export const initialSceneId: SceneId = "";
